---
title: "index"
author: "Pierina Forastieri and Sylvia Brown"
date: "2/19/2022"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

```

```{r include = FALSE}
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})

```

\begin{center}
\Huge{PPOL 670 | Assignment 4}

\Huge{Data Visualization, Markdown, and Git}
\end{center}

\vspace{0.1in}

```{r}
library(tidyverse)
library(janitor)

```


# Dataset selection

```{r}
data <- read_csv("data/Download-data-in-Excel.csv")

data <- data %>%
  janitor::clean_names()

data <- data %>%
  filter(economy == "Argentina" |  economy == "Bolivia" |  economy == "Brazil" |  economy == "Chile" |  economy == "Colombia" |  economy == "Costa Rica" |  economy == "Dominican Rep." |  economy == "Ecuador" |  economy == "El Salvador" |  economy == "Guatemala" |  economy == "Honduras "|  economy == "Mexico" |  economy == "Nicaragua" |  economy == "Panama"|  economy == "Paraguay" |  economy == "Peru" |  economy == "Puerto Rico" |  economy == "Uruguay" |  economy == "Venezuela")
```

\newpage

# Four ggplot2 graphs (4 points)

## Graph 01: 

```{r}



```

\newpage

## Graph 02: 

\newpage

# Exercise 04 (2 points)

\newpage

# Exercise 05 (2 points)
